spring:
  application:
    name: 2026_Silver_Residence


  ai:
    model:
      chat: openai
    openai:
      base-url: https://kuaipao.pro/v1
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.1
          maxTokens: 512

  data:
    mongodb:
      host: localhost
      database: Silver
      port: 27017
